# --- Spring Boot specific properties for local ---

logs:
  base:
    dir: logs

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ${poker.datasource.password}
    url: jdbc:h2:mem:poker
    username: spring-boot-local
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath*:schema-h2.sql