# --- Application specific properties per environment ---
# Adjust logging levels in file logback-spring.xml
 
build:
  name: '@build.number@'
  version: '@project.version@'
  timestamp: '@build.timestamp@'

logging:
  level:
    root: info
    '[net.zoostar]': trace
    '[com.zoostarinc]': trace
  logback:
    rollingpolicy:
      file-name-pattern: "logs/archive/@project.build.finalName@-%d{yyyy-MM-dd}.%i.log.zip"
  file:
    name: "logs/@project.build.finalName@.log"

spring:
  output:
    ansi:
      enabled: always
  profiles:
    active:
      - local # Load spring boot profile by default
  datasource:
    driver-class-name: org.h2.Driver
    username: poker
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath*:schema-h2.sql
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1080880909532-ah9opvtako4kavm3o8gfr91vumipbc8a.apps.googleusercontent.com
            clientSecret: ${client.secret.poker.google}
            scope:
              - openid
              - profile
              - email
