logging:
  file:
    name: "logs/@project.build.finalName@.log"
  level:
    root: info
    '[net.zoostar]': debug
    '[com.zoostarinc]': debug

logs:
  base:
    dir: logs

server:
  forward-headers-strategy: framework
