logging:
  file:
    path: logs
    name: "@project.build.finalName@"
  level:
    root: info
    '[net.zoostar]': debug
    '[com.zoostarinc]': debug

logs:
  base:
    dir: logs

server:
  forward-headers-strategy: framework
