# --- Spring Boot specific properties for sandbox ---

logs:
  base:
    dir: logs

logging:
  level:
    root: info
    '[net.zoostar]': trace
    '[com.zoostarinc]': trace
    '[org.springframework.security]': debug
    '[org.springframework.transaction]': trace
