# --- Spring Boot specific properties for local ---
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048

spring:
  datasource:
    password: ${poker.datasource.password}
    url: jdbc:h2:mem:poker
