# --- Application specific properties per environment ---
build:
  name: '@build.number@'
  version: '@project.version@'
  timestamp: '@build.timestamp@'

spring:
  profiles:
    active:
      - local # Load spring boot profile by default
